name: colreg_xai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12                # Versione stabile per ML-Agents e RTAMT
  - pip
  - numpy<2.0.0                  # Fondamentale per la compatibilitÃ  con ML-Agents 1.1.0
  - pytorch                      
  - torchvision
  - matplotlib
  - tqdm                         # Progress bar per il training
  - grpcio>=1.48.2               # Installato via Conda per evitare errori di compilazione su M4
  - protobuf==3.20.3             # Versione specifica richiesta da ML-Agents
  - pip:
      - mlagents==1.1.0          # La versione del simulatore Unity
      - mlagents-envs==1.1.0
      - rtamt                    # logica STL 